//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikosSistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Nationality { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> Style { get; set; }
        public string Role { get; set; }
        public string InfoPage { get; set; }
        public int SongArtist { get; set; }
    
        public virtual SongArtist SongArtist1 { get; set; }
        public virtual Style Style1 { get; set; }
    }
}
