//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikosSistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListenerStyles
    {
        public int Id { get; set; }
        public int Listener { get; set; }
        public int Style { get; set; }
    
        public virtual ListenerProfile ListenerProfile { get; set; }
        public virtual Style Style1 { get; set; }
    }
}
