//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikosSistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongRecomandation
    {
        public int Id { get; set; }
        public int Song { get; set; }
        public int Recomandation { get; set; }
        public int Rank { get; set; }
    
        public virtual Song Song1 { get; set; }
        public virtual Song Song2 { get; set; }
    }
}
